"""added inducements table, updated affliliations

Revision ID: 45839064e8d9
Revises: 92219522df3a
Create Date: 2026-09-27 15:41:27.835420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45839064e8d9'
down_revision: Union[str, Sequence[str], None] = '92219522df3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inducements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), unique=True, nullable=False),
    sa.Column('max_allowed', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inducements_affiliations',
    sa.Column('inducement_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['inducement_id'], ['inducements.id'], ),
    sa.PrimaryKeyConstraint('inducement_id', 'affiliation_id')
    )
    op.drop_column('affiliations', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliations', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_table('inducements_affiliations')
    op.drop_table('inducements')
    # ### end Alembic commands ###
