"""added dungeon bowl race table, updated affliliations

Revision ID: 546f8acd5dd6
Revises: ffc7dc961a2f
Create Date: 2026-09-27 16:49:46.194354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546f8acd5dd6'
down_revision: Union[str, Sequence[str], None] = 'ffc7dc961a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('reroll_cost', sa.Integer(), nullable=True),
    sa.Column('apothecary_allowed', sa.Boolean(), default=True),
    sa.Column('special_rule_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dungeon_bowl_affiliations',
    sa.Column('db_race_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['db_race_id'], ['db_races.id'], ),
    sa.PrimaryKeyConstraint('db_race_id', 'affiliation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dungeon_bowl_affiliations')
    op.drop_table('db_races')
    # ### end Alembic commands ###
