"""added dungeon bowl positions table, updated affliliations

Revision ID: 8c088b9ea61a
Revises: 546f8acd5dd6
Create Date: 2026-09-27 16:50:39.123699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c088b9ea61a'
down_revision: Union[str, Sequence[str], None] = '546f8acd5dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeon_bowl_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_race_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_allowed', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('skill_list', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('primary_access', sa.String(length=100), nullable=False),
    sa.Column('secondary_access', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['db_race_id'], ['db_races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeon_bowl_positions_id'), 'dungeon_bowl_positions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dungeon_bowl_positions_id'), table_name='dungeon_bowl_positions')
    op.drop_table('dungeon_bowl_positions')
    # ### end Alembic commands ###
