"""added star players and affiliations table, update races to use affliliations

Revision ID: 92219522df3a
Revises: 8c2d828de2ee
Create Date: 2026-09-27 15:29:37.229253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92219522df3a'
down_revision: Union[str, Sequence[str], None] = '8c2d828de2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('star_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_allowed', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('skill_list', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('upkeep', sa.Integer(), nullable=False),
    sa.Column('special_rule', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('race_affiliations',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'affiliation_id')
    )
    op.create_table('star_player_affiliations',
    sa.Column('star_player_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['star_player_id'], ['star_players.id'], ),
    sa.PrimaryKeyConstraint('star_player_id', 'affiliation_id')
    )
    op.drop_column('races', 'affiliated_league')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('affiliated_league', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('star_player_affiliations')
    op.drop_table('race_affiliations')
    op.drop_table('star_players')
    op.drop_table('affiliations')
    # ### end Alembic commands ###
