"""add and update tables

Revision ID: a23ea549fea8
Revises: c83f1809565c
Create Date: 2026-09-27 14:41:11.711558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23ea549fea8'
down_revision: Union[str, Sequence[str], None] = 'c83f1809565c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('tier', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('reroll_cost', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('affiliated_league', sa.String(length=100), nullable=True))
    op.add_column('races', sa.Column('apothecary_allowed', sa.Boolean(), default=True))
    op.add_column('races', sa.Column('special_rule_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'special_rule_text')
    op.drop_column('races', 'apothecary_allowed')
    op.drop_column('races', 'affiliated_league')
    op.drop_column('races', 'reroll_cost')
    op.drop_column('races', 'tier')
    # ### end Alembic commands ###
