"""add unique constraint to inducements, mercenaries and dungeon bowl name. changed apothecary to default and not nullable

Revision ID: d28acd07f198
Revises: 8c088b9ea61a
Create Date: 2026-09-27 17:20:10.634504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28acd07f198'
down_revision: Union[str, Sequence[str], None] = '8c088b9ea61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dungeon_bowl_positions', ['name'])
    op.create_unique_constraint(None, 'mercenaries', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'mercenaries', type_='unique')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'dungeon_bowl_positions', type_='unique')
    # ### end Alembic commands ###
