"""added mercenary table, updated affliliations

Revision ID: ffc7dc961a2f
Revises: 45839064e8d9
Create Date: 2026-09-27 16:29:51.455475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc7dc961a2f'
down_revision: Union[str, Sequence[str], None] = '45839064e8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercenaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_allowed', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('skill_list', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('upkeep', sa.Integer(), nullable=False),
    sa.Column('special_rule', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mercenaries_id'), 'mercenaries', ['id'], unique=False)
    op.create_table('mercenary_affiliations',
    sa.Column('mercenary_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['mercenary_id'], ['mercenaries.id'], ),
    sa.PrimaryKeyConstraint('mercenary_id', 'affiliation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mercenary_affiliations')
    op.drop_index(op.f('ix_mercenaries_id'), table_name='mercenaries')
    op.drop_table('mercenaries')
    # ### end Alembic commands ###
